#!/usr/bin/env sh

FIFO="$XDG_RUNTIME_DIR/sandbar"
[ -e "$FIFO" ] && rm -f "$FIFO"
mkfifo "$FIFO"

while cat "$FIFO"; do :; done | sandbar \
    -font "IBM Plex Mono:style=Bold:size=14" \
	-active-fg-color "#000000" \
	-active-bg-color "#306850" \
	-inactive-fg-color "#e0f8cf" \
	-inactive-bg-color "#000000" \
	-urgent-fg-color "#000000" \
	-urgent-bg-color "#cc241d" \
	-title-fg-color "#000000" \
	-title-bg-color "#306850"

# Old color table
#	-active-fg-color "#000000" \
#	-active-bg-color "#98971a" \
#	-inactive-fg-color "#ebdbb2" \
#	-inactive-bg-color "#000000" \
#	-urgent-fg-color "#000000" \
#	-urgent-bg-color "#cc241d" \
#	-title-fg-color "#000000" \
#	-title-bg-color "#98971a"


