#!/usr/bin/env sh

datetime() {
	datetime="$(date "+%a %d %b %I:%M %P")"
}

bat() {
	read -r bat_status </sys/class/power_supply/BAT0/status
	read -r bat_capacity </sys/class/power_supply/BAT0/capacity
	bat="$bat_status $bat_capacity%"
}

vol() {
	vol="$([ "$(wpctl get-volume @DEFAULT_SINK@ | awk '{print $3}')" = "[MUTED]" ] && printf "%s" "MUTED" || printf "%s%%" "$(wpctl get-volume @DEFAULT_SINK@ | awk '{print $2}')")"
}

bright() {
	bright="$(brightnessctl| awk 'NR==2 {print $4}' | grep -Eo '[0-9]+')"
}

display() {
	echo "all status Bat:[$bat] Bri:[$bright%] Vol:[$vol] [$datetime]" >"$FIFO"
}

printf "%s" "$$" > "$XDG_RUNTIME_DIR/status_pid"
FIFO="$XDG_RUNTIME_DIR/sandbar"
[ -e "$FIFO" ] || mkfifo "$FIFO"
sec=0

while true; do
	sleep 1 &
	wait && {
		[ $((sec % 60)) -eq 0 ] && bat
		[ $((sec % 5)) -eq 0 ] && vol
		[ $((sec % 5)) -eq 0 ] && bright
		[ $((sec % 5)) -eq 0 ] && datetime

		[ $((sec % 5)) -eq 0 ] && display

		sec=$((sec + 1))
	}
done
